### ISSUE TITLE
你好，在 BS游戏资源共享 中没有找到联机相关的mod，是已经过期了吗？

### ISSUE THREAD

**Issue by iT-Boyer** [MicroCBer/QuestPatcher#2]
BeatTogether | 【联机】用于支持通过第三方服务器联机

MultiQuestensions | 【联机】用于支持自定义歌曲联机，支持自动下载歌曲

ServerBrowser | 【联机】房间列表

![BS游戏资源共享](https://bs.wgzeyu.com/oq-guide-bmbf/)

![Mod相关文件](https://zfile.imoto.love/2/main/Mod%E7%9B%B8%E5%85%B3%E6%96%87%E4%BB%B6/%E3%80%90Quest%E4%B8%80%E4%BD%93%E6%9C%BA%E5%B9%B3%E5%8F%B0%E3%80%911.21.0%20%E7%89%88%E6%9C%AC%E3%80%90%E6%9C%80%E6%96%B0%E7%89%88%E3%80%91)

**Comment by MicroCBer** [comment]
目前quest2联机仅支持到`1.17.1`

另外 这和qp没有什么关系 别在这问 去群里问

**Comment by WGzeyu** [comment]
1. 这个问题与QuestPatcher无关
2. 联机相关的Mod目前还只支持到1.17.1版本的Beat Saber
3. Mod开发者正在尝试适配最新版，但开发没那么快
4. 网盘里不会有本来就不存在的东西，如果现在就想用联机mod，可以先降级1.17.1

**Comment by iT-Boyer** [comment]
好的，怎么加群？

**Comment by MicroCBer** [comment]
810303476

**Comment by WGzeyu** [comment]
教程右上角
[https://bs.wgzeyu.com/](https://bs.wgzeyu.com/)

**Comment by iT-Boyer** [comment]
谢谢，两位。
