### ISSUE TITLE
最新版本是不是无法使用

### ISSUE THREAD

**Issue by Konne06** [MicroCBer/QuestPatcher#20]
Q3 系统为最新 游戏尝试降级到1.28和1.71都试过
这个和bmbf都装不上
这个具体体现出来是 修改apk似乎是成功了（会有恢复警告）
但没有一个mod生效  进游戏仍然是原版

**Comment by qe201020335** [comment]
Q3 目前无法打mod
![image](https://github.com/MicroCBer/QuestPatcher/assets/31044781/f507954a-1c3f-46c5-804c-078ac7a4cd5c)

**Comment by Konne06** [comment]
> Q3目前无法打mod ![图像](https://user-images.githubusercontent.com/31044781/277154072-f507954a-1c3f-46c5-804c-078ac7a4cd5c.png)

已经可以了 b站有人出了教程 结合原版的questpatcher加上手动一些adb命令

**Comment by qe201020335** [comment]
Q3 modding相关的工具还在开发中

如果你了解adb而且愿意自己解决文件权限问题，你可以自己弄
