### ISSUE TITLE
提示缺少libunity.so

### ISSUE THREAD

**Issue by YostGray** [MicroCBer/QuestPatcher#23]
![image](https://github.com/MicroCBer/QuestPatcher/assets/37040861/f4bade1d-50e4-4d26-a1c7-8e712d46f9d4)
patch时如图，请问是什么问题呀？

**Comment by qe201020335** [comment]
看截图里的日志，看起来是请求unity版本的时候失败了。

可能是网络问题。

我这边也会尝试复现
