### ISSUE TITLE
关于支持库版本不同时的决策更改

### ISSUE THREAD

**Issue by WGzeyu** [MicroCBer/QuestPatcher#9]
根据测试，
当QuestPatcher触发检查核心Mod时，会在检查过程中将版本与核心清单中版本不同的核心Mod删掉（估计是以前出过跨版本安装核心mod崩溃的问题的时候做的），无论是否点击帮我补全，只要触发了核心mod检查步骤，就会导致版本不同的核心mod被删掉（之后如果点击帮我补全，就会将核心Mod安装为核心列表中的版本）
QP拖入安装任何Mod，都会先触发核心Mod检查步骤，另外，在检查依赖的步骤也会进行降级安装，将已安装的更高版本覆盖为应用指定的旧版
而BMBF，无论是检查核心Mod，还是检查依赖，都是只会进行升级安装，不会进行降级安装。

**BMBF与QuestPatcher的具体区别是**：
（核心列表中QuestUI版本为0.17.4、anytweaks指定的QuestUI版本为0.17.5、PolyglotInject没有指定QuestUI、JDFixer指定的QuestUI版本为0.17.4，**以下操作均为按序号顺序执行，并不是按先后顺序执行**）

　1.​ **初次安装核心Mod**：
　　QP的QuestUI为0.17.4，BMBF也为0.17.4
　2. **安装anytweaks**：
　　QP的QuestUI会被升级为0.17.5，BMBF也会升级为0.17.5
　3. **点击检查核心Mod**：
　　BMBF不会做出改变，QuestUI仍然为0.17.5；而QP会将0.17.5的QuestUI直接卸载掉
　　（然后QP在点击“帮我补全”后，才会下载0.17.4的QuestUI）
　3. **安装PolyglotInject**：
　　BMBF不会做出改变，QuestUI仍然为0.17.5；而QP会将0.17.5的QuestUI直接卸载掉
　　（然后QP在QP点击“帮我补全”后，才会下载0.17.4的QuestUI）
　3. **安装JDFixer**：
　　BMBF不会做出改变，QuestUI仍然为0.17.5；而QP会将0.17.5的QuestUI直接卸载掉
　　（然后QP在QP点击“帮我补全”或“取消”后，均会下载0.17.4的QuestUI）

**我认为做出以下更改，将可以减少问题发生**：（如不同Mod组合使用会导致游戏闪退打不开）
1. 将“检查核心Mod”过程中目前的“核心Mod版本不同时卸载”**改为**：
“已安装的某个核心Mod版本低于核心列表中的版本时弹出提示框”
“已安装的某个核心Mod版本在核心列表中不存在于当前游戏版本，却存在于不同的游戏版本时弹出提示框”
提示框为 “当前已安装的核心Mod可能不兼容您的游戏版本，是否将其全部卸载？（卸载后你可以一键安装版本匹配的核心Mod）” ，若点击是，则全部卸载，若点击忽略，则忽略
2. 在“检查核心Mod”过程中，如果已安装的核心Mod版本高于核心列表中的版本，则同样判断为版本匹配的核心Mod
（还有个如果核心Mod被关闭，则将其打开的步骤，同样将更高版本的核心Mod也算作核心Mod一起打开）
3. 在“补全核心Mod”过程中，如果已安装的核心Mod版本高于核心列表中的版本，则忽略该Mod
4. 在“安装Mod”过程中的“检查依赖”步骤中，如果已安装的支持库高于应用要求的支持库，不要做降级安装，只可以升级安装（原版qp暂时还没测试，不知道是不是有相同问题）
5. 在“安装Mod”过程中的“检查依赖”步骤中，如果应用要求的支持库中有核心Mod，且版本与核心列表中的版本不同，则做出警告提示：
“您正要安装的xxxx引用了xxxx版本的核心Mod xxxx，然而这个版本与核心Mod列表中的版本xxxx不同，继续安装可能会造成兼容性问题，也可能可以正常使用。”
“继续”“取消”

（做完这些更改后，理论来说QP与BMBF在刚才测试中的行为将会变的完全相同）

**Comment by qe201020335** [comment]
一键降级将会删除所有已有mod，在提示窗里加入以下警告
“降级后会删除所有的Mod，但不会影响您的歌曲、模型资源；降级完成后您可以把对应版本的Mod重新装回去，即可继续使用这些资源。”
